### ISSUE TITLE
Property 'xxx' has no initializer and is not definitely assigned in the constructor.ts(2564)

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [omermorad/mockingbird#90]
```typescript
import { Mock, MockFactory } from 'mockingbird-ts';
class Something implements SomethingElse {
  @Mock()
   xxx: string;
}
export const oneX = MockFactory(Something).one();
```
Property 'xxx' has no initializer and is not definitely assigned in the constructor.ts(2564)

How do I get around that

**Comment by omermorad** [comment]
Hi @sschneider-ihre-pvs

Thanks for submitting this issue, can you please detail what version are you using?
Is this the complete code you are using? I will appreciate if you can provide the full snippet

**Comment by sschneider-ihre-pvs** [comment]
yes, I found a workaround with using `!` for the ts compiler.
